DROP TABLE EVENT_LOG_ALERT IF EXISTS;

CREATE TABLE EVENT_LOG_ALERT  (
    EVENT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    EVENT_TYPE VARCHAR(8) NULL,
    EVENT_HOST VARCHAR(20) NULL,
    EVENT_ALRT VARCHAR(5),
    EVENT_DURATION BIGINT 
);